{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword }}
{{- end }}
