{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp-color.fullname" . }}
  labels:
    {{- include "webapp-color.labels" . | nindent 4 }}
data:
  APP_COLOR: {{ .Values.configMap.appColor }}
{{- end }}
