apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: simpleapp
  namespace: lab-8
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30088
  selector:
    run: webapp
  type: NodePort
