apiVersion: v1
kind: Service
metadata:
  labels:
    svc: httpd-service
  name: httpd
  namespace: lab-7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    tier: frontend
  type: NodePort
